UPDATE CATEGORIES
SET
   CATEGORY_NAME = ?
 , CATEGORY_ICON = ?
 , DESCRIPTION = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE
CATEGORY_ID = ?
;
